# Generated by Django 3.1.3 on 2020-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=50)),
                ('donorMobile', models.CharField(max_length=15)),
                ('donorAge', models.IntegerField()),
                ('donorAddress', models.TextField(max_length=150)),
                ('donorCity', models.CharField(max_length=30)),
                ('donorBloodgroup', models.CharField(max_length=4)),
                ('donorSex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('donorCovidrecord', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('donorScreening', models.DateField()),
                ('donorStatus', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
    ]
