# Generated by Django 3.1.3 on 2020-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverName', models.CharField(max_length=50)),
                ('receiverAge', models.IntegerField()),
                ('receiverHospital', models.TextField(max_length=200)),
                ('receiverAddress', models.TextField(max_length=250)),
                ('receiverCity', models.CharField(max_length=30)),
                ('receiverBloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('receiverCaretaker', models.CharField(max_length=50)),
                ('receiverCaretakercontact', models.CharField(max_length=15)),
                ('receiverCaretakeremail', models.CharField(max_length=30)),
                ('receiverDocs', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='donors',
            name='donorBloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
